<?php
require('../lib/base.php');

jn_query("UPDATE PS5297 SET STATUS_ARQUIVO = 'N' WHERE COALESCE(STATUS_ARQUIVO, 'P') = 'P' AND PS5297.NUMERO_REGISTRO IN (SELECT NUMERO_REGISTRO_PS5297 FROM PS5298 WHERE COALESCE(FLAG_APENAS_REGISTRO, 'N') = 'N')");
jn_query("UPDATE PS5297 SET STATUS_ARQUIVO = 'A' WHERE COALESCE(STATUS_ARQUIVO, 'P') = 'P' AND PS5297.NUMERO_REGISTRO NOT IN (SELECT NUMERO_REGISTRO_PS5297 FROM PS5298 WHERE COALESCE(FLAG_APENAS_REGISTRO, 'N') = 'N')");

?>